name: "run tests"

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ develop ]

concurrency:
  group: ci-dev-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dev-test:
    runs-on: ubuntu-latest
    permissions: # Necessary for workload identity provider
      contents: 'read'
      id-token: 'write'
    steps:
      # 1. Setup
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'liberica'
          java-version: '21'
          cache: 'maven'
      
      # 2. Run tests
      - name: Run Unit & Integration Tests
        run: mvn clean verify --no-transfer-progress
      
      # 3. Auth
      - name: Auth via Workload Identity Federation
        id: auth
        uses: google-github-actions/auth@v2.1.2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }} # impersonated SA

      # 4. Setup gcloud & configure docker to use gcloud
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
      - name: Setup docker to authenticate via gcloud
        run: gcloud --quiet auth configure-docker us-docker.pkg.dev

      # 5. Build image
      - name: Build image
        run: mvn clean package -DskipTests spring-boot:build-image --no-transfer-progress -Dspring-boot.build-image.imageName=$IMAGE_REGISTRY:$IMAGE_TAG

      # 6. Push image
      - name: Push image
        run: docker push $IMAGE_REGISTRY:$IMAGE_TAG