name: "deploy to dev"

# Note: Execute when feature branch is merge into develop this CI will be executed.

on:
  pull_request:
    types: [ closed ]
    branches: [ develop ]

env:
  IMAGE_NAME: api

concurrency:
  group: ci-deploy-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    environment: dev
    if: github.event.pull_request.merged == true
    outputs:
      IMAGE_TAG: ${{ steps.variables.outputs.IMAGE_TAG }}
      IMAGE_REGISTRY: ${{ steps.variables.outputs.IMAGE_REGISTRY }}
    
    # Necessary for workload identity provider
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      
      # 1. Setup
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'liberica'
          java-version: '21'
          cache: 'maven'
      
      # 2.1. Sets variables
      - name: Sets release variables
        id: variables
        run: |
          # 1. Set vars
          IMAGE_REGISTRY="us-docker.pkg.dev/${{ secrets.PROJECT_ID }}/cloud-diplomats/${{ env.IMAGE_NAME }}"
          IMAGE_TAG="dev-${{ github.run_number }}"
          
          # 2. Set envs & outputs
          echo "IMAGE_REGISTRY=$IMAGE_REGISTRY" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "IMAGE_REGISTRY=${IMAGE_REGISTRY}" >> $GITHUB_OUTPUT
      
      # 2.2. Echo variables
      - name: Echo variables
        run: |
          echo "IMAGE_TAG=$IMAGE_TAG"
          echo "IMAGE_REGISTRY=$IMAGE_REGISTRY"
      
      # 3. Auth
      - name: Auth via Workload Identity Federation
        id: auth
        uses: google-github-actions/auth@v1.2.0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }} # impersonated SA
      
      # 4.1. Setup gcloud
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          project_id: ${{ secrets.PROJECT_ID }}
      
      # 4.2. Configure docker to use gcloud as a credential helper
      - name: Setup docker to authenticate via gcloud
        run: gcloud --quiet auth configure-docker us-docker.pkg.dev
      
      # 5. Build image using maven
      - name: Build image
        run: mvn clean package -DskipTests spring-boot:build-image --no-transfer-progress -Dspring-boot.build-image.imageName=$IMAGE_REGISTRY:$IMAGE_TAG
      
      # 6. Push image to registry
      - name: Push image to registry
        run: docker push $IMAGE_REGISTRY:$IMAGE_TAG
      
      # 7. Notify if fails
      #      - name: Notify slack fail
      #        if: failure()
      #        env:
      #          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      #        uses: voxmedia/github-action-slack-notify-build@v1
      #        with:
      #          channel: app-alerts
      #          status: FAILED
      #          color: danger